<?php
/**
 * PhishingDetectionAdvancedRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * PhishingDetectionAdvancedRequest Class Doc Comment
 *
 * @category Class
 * @description AI advanced phishing detection request
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PhishingDetectionAdvancedRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PhishingDetectionAdvancedRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'input_string' => 'string',
        'text_type' => 'string',
        'model' => 'string',
        'allow_unsolicited_sales' => 'bool',
        'allow_promotional_content' => 'bool',
        'allow_web_urls' => 'bool',
        'allow_phone_numbers' => 'bool',
        'allow_email_addresses' => 'bool',
        'provide_url_analysis' => 'bool',
        'custom_policy_id' => 'string',
        'provide_analysis_rationale' => 'bool',
        'from_name' => 'string',
        'to_name' => 'string',
        'from_phone_number' => 'string',
        'to_phone_number' => 'string',
        'from_email_address' => 'string',
        'to_email_address' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'input_string' => null,
        'text_type' => null,
        'model' => null,
        'allow_unsolicited_sales' => null,
        'allow_promotional_content' => null,
        'allow_web_urls' => null,
        'allow_phone_numbers' => null,
        'allow_email_addresses' => null,
        'provide_url_analysis' => null,
        'custom_policy_id' => null,
        'provide_analysis_rationale' => null,
        'from_name' => null,
        'to_name' => null,
        'from_phone_number' => null,
        'to_phone_number' => null,
        'from_email_address' => null,
        'to_email_address' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'input_string' => 'InputString',
        'text_type' => 'TextType',
        'model' => 'Model',
        'allow_unsolicited_sales' => 'AllowUnsolicitedSales',
        'allow_promotional_content' => 'AllowPromotionalContent',
        'allow_web_urls' => 'AllowWebUrls',
        'allow_phone_numbers' => 'AllowPhoneNumbers',
        'allow_email_addresses' => 'AllowEmailAddresses',
        'provide_url_analysis' => 'ProvideUrlAnalysis',
        'custom_policy_id' => 'CustomPolicyID',
        'provide_analysis_rationale' => 'ProvideAnalysisRationale',
        'from_name' => 'FromName',
        'to_name' => 'ToName',
        'from_phone_number' => 'FromPhoneNumber',
        'to_phone_number' => 'ToPhoneNumber',
        'from_email_address' => 'FromEmailAddress',
        'to_email_address' => 'ToEmailAddress'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'input_string' => 'setInputString',
        'text_type' => 'setTextType',
        'model' => 'setModel',
        'allow_unsolicited_sales' => 'setAllowUnsolicitedSales',
        'allow_promotional_content' => 'setAllowPromotionalContent',
        'allow_web_urls' => 'setAllowWebUrls',
        'allow_phone_numbers' => 'setAllowPhoneNumbers',
        'allow_email_addresses' => 'setAllowEmailAddresses',
        'provide_url_analysis' => 'setProvideUrlAnalysis',
        'custom_policy_id' => 'setCustomPolicyId',
        'provide_analysis_rationale' => 'setProvideAnalysisRationale',
        'from_name' => 'setFromName',
        'to_name' => 'setToName',
        'from_phone_number' => 'setFromPhoneNumber',
        'to_phone_number' => 'setToPhoneNumber',
        'from_email_address' => 'setFromEmailAddress',
        'to_email_address' => 'setToEmailAddress'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'input_string' => 'getInputString',
        'text_type' => 'getTextType',
        'model' => 'getModel',
        'allow_unsolicited_sales' => 'getAllowUnsolicitedSales',
        'allow_promotional_content' => 'getAllowPromotionalContent',
        'allow_web_urls' => 'getAllowWebUrls',
        'allow_phone_numbers' => 'getAllowPhoneNumbers',
        'allow_email_addresses' => 'getAllowEmailAddresses',
        'provide_url_analysis' => 'getProvideUrlAnalysis',
        'custom_policy_id' => 'getCustomPolicyId',
        'provide_analysis_rationale' => 'getProvideAnalysisRationale',
        'from_name' => 'getFromName',
        'to_name' => 'getToName',
        'from_phone_number' => 'getFromPhoneNumber',
        'to_phone_number' => 'getToPhoneNumber',
        'from_email_address' => 'getFromEmailAddress',
        'to_email_address' => 'getToEmailAddress'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['input_string'] = isset($data['input_string']) ? $data['input_string'] : null;
        $this->container['text_type'] = isset($data['text_type']) ? $data['text_type'] : null;
        $this->container['model'] = isset($data['model']) ? $data['model'] : null;
        $this->container['allow_unsolicited_sales'] = isset($data['allow_unsolicited_sales']) ? $data['allow_unsolicited_sales'] : null;
        $this->container['allow_promotional_content'] = isset($data['allow_promotional_content']) ? $data['allow_promotional_content'] : null;
        $this->container['allow_web_urls'] = isset($data['allow_web_urls']) ? $data['allow_web_urls'] : null;
        $this->container['allow_phone_numbers'] = isset($data['allow_phone_numbers']) ? $data['allow_phone_numbers'] : null;
        $this->container['allow_email_addresses'] = isset($data['allow_email_addresses']) ? $data['allow_email_addresses'] : null;
        $this->container['provide_url_analysis'] = isset($data['provide_url_analysis']) ? $data['provide_url_analysis'] : null;
        $this->container['custom_policy_id'] = isset($data['custom_policy_id']) ? $data['custom_policy_id'] : null;
        $this->container['provide_analysis_rationale'] = isset($data['provide_analysis_rationale']) ? $data['provide_analysis_rationale'] : null;
        $this->container['from_name'] = isset($data['from_name']) ? $data['from_name'] : null;
        $this->container['to_name'] = isset($data['to_name']) ? $data['to_name'] : null;
        $this->container['from_phone_number'] = isset($data['from_phone_number']) ? $data['from_phone_number'] : null;
        $this->container['to_phone_number'] = isset($data['to_phone_number']) ? $data['to_phone_number'] : null;
        $this->container['from_email_address'] = isset($data['from_email_address']) ? $data['from_email_address'] : null;
        $this->container['to_email_address'] = isset($data['to_email_address']) ? $data['to_email_address'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets input_string
     *
     * @return string
     */
    public function getInputString()
    {
        return $this->container['input_string'];
    }

    /**
     * Sets input_string
     *
     * @param string $input_string Input text string to detect phishing against
     *
     * @return $this
     */
    public function setInputString($input_string)
    {
        $this->container['input_string'] = $input_string;

        return $this;
    }

    /**
     * Gets text_type
     *
     * @return string
     */
    public function getTextType()
    {
        return $this->container['text_type'];
    }

    /**
     * Sets text_type
     *
     * @param string $text_type Optional: Type of text being analyzed. Must be one of: \"TextMessage\", \"UserMessage\", \"SalesLead\", \"EmailMessage\", \"SupportCase\", \"AppMessage\", \"Other\".
     *
     * @return $this
     */
    public function setTextType($text_type)
    {
        $this->container['text_type'] = $text_type;

        return $this;
    }

    /**
     * Gets model
     *
     * @return string
     */
    public function getModel()
    {
        return $this->container['model'];
    }

    /**
     * Sets model
     *
     * @param string $model Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced.
     *
     * @return $this
     */
    public function setModel($model)
    {
        $this->container['model'] = $model;

        return $this;
    }

    /**
     * Gets allow_unsolicited_sales
     *
     * @return bool
     */
    public function getAllowUnsolicitedSales()
    {
        return $this->container['allow_unsolicited_sales'];
    }

    /**
     * Sets allow_unsolicited_sales
     *
     * @param bool $allow_unsolicited_sales Optional: True if unsolicited sales should be allowed, false otherwise. Defaults to true.
     *
     * @return $this
     */
    public function setAllowUnsolicitedSales($allow_unsolicited_sales)
    {
        $this->container['allow_unsolicited_sales'] = $allow_unsolicited_sales;

        return $this;
    }

    /**
     * Gets allow_promotional_content
     *
     * @return bool
     */
    public function getAllowPromotionalContent()
    {
        return $this->container['allow_promotional_content'];
    }

    /**
     * Sets allow_promotional_content
     *
     * @param bool $allow_promotional_content Optional: True if promotional content should be allowed, false otherwise. Defaults to true.
     *
     * @return $this
     */
    public function setAllowPromotionalContent($allow_promotional_content)
    {
        $this->container['allow_promotional_content'] = $allow_promotional_content;

        return $this;
    }

    /**
     * Gets allow_web_urls
     *
     * @return bool
     */
    public function getAllowWebUrls()
    {
        return $this->container['allow_web_urls'];
    }

    /**
     * Sets allow_web_urls
     *
     * @param bool $allow_web_urls Optional: True if web URLs should be allowed in the input text, false otherwise. Defaults to true. When false, input containing URLs (including homoglyph URLs and spaced-out URLs) will be flagged as not clean.
     *
     * @return $this
     */
    public function setAllowWebUrls($allow_web_urls)
    {
        $this->container['allow_web_urls'] = $allow_web_urls;

        return $this;
    }

    /**
     * Gets allow_phone_numbers
     *
     * @return bool
     */
    public function getAllowPhoneNumbers()
    {
        return $this->container['allow_phone_numbers'];
    }

    /**
     * Sets allow_phone_numbers
     *
     * @param bool $allow_phone_numbers Optional: True if phone numbers should be allowed in the input text, false otherwise. Defaults to true. When false, input containing phone numbers (including homoglyph digits and spaced-out or spelled-out workarounds) will be flagged as not clean.
     *
     * @return $this
     */
    public function setAllowPhoneNumbers($allow_phone_numbers)
    {
        $this->container['allow_phone_numbers'] = $allow_phone_numbers;

        return $this;
    }

    /**
     * Gets allow_email_addresses
     *
     * @return bool
     */
    public function getAllowEmailAddresses()
    {
        return $this->container['allow_email_addresses'];
    }

    /**
     * Sets allow_email_addresses
     *
     * @param bool $allow_email_addresses Optional: True if email addresses should be allowed in the input text, false otherwise. Defaults to true. When false, input containing email addresses (including homoglyph characters and obfuscated workarounds like \"danny at somedomaine [DOT] com\") will be flagged as not clean.
     *
     * @return $this
     */
    public function setAllowEmailAddresses($allow_email_addresses)
    {
        $this->container['allow_email_addresses'] = $allow_email_addresses;

        return $this;
    }

    /**
     * Gets provide_url_analysis
     *
     * @return bool
     */
    public function getProvideUrlAnalysis()
    {
        return $this->container['provide_url_analysis'];
    }

    /**
     * Sets provide_url_analysis
     *
     * @param bool $provide_url_analysis Optional: True to perform deep URL analysis on any URLs detected in the text. When enabled, if the initial AI scan detects URLs, a second AI call enumerates them and each URL is individually analyzed for phishing. Defaults to true.
     *
     * @return $this
     */
    public function setProvideUrlAnalysis($provide_url_analysis)
    {
        $this->container['provide_url_analysis'] = $provide_url_analysis;

        return $this;
    }

    /**
     * Gets custom_policy_id
     *
     * @return string
     */
    public function getCustomPolicyId()
    {
        return $this->container['custom_policy_id'];
    }

    /**
     * Sets custom_policy_id
     *
     * @param string $custom_policy_id Apply a Custom Policy for Phishing Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud
     *
     * @return $this
     */
    public function setCustomPolicyId($custom_policy_id)
    {
        $this->container['custom_policy_id'] = $custom_policy_id;

        return $this;
    }

    /**
     * Gets provide_analysis_rationale
     *
     * @return bool
     */
    public function getProvideAnalysisRationale()
    {
        return $this->container['provide_analysis_rationale'];
    }

    /**
     * Sets provide_analysis_rationale
     *
     * @param bool $provide_analysis_rationale Optional: Set to true to include an analysis rationale in the response explaining why the content was or was not flagged.  Default is true.
     *
     * @return $this
     */
    public function setProvideAnalysisRationale($provide_analysis_rationale)
    {
        $this->container['provide_analysis_rationale'] = $provide_analysis_rationale;

        return $this;
    }

    /**
     * Gets from_name
     *
     * @return string
     */
    public function getFromName()
    {
        return $this->container['from_name'];
    }

    /**
     * Sets from_name
     *
     * @param string $from_name Optional: Name of the sender
     *
     * @return $this
     */
    public function setFromName($from_name)
    {
        $this->container['from_name'] = $from_name;

        return $this;
    }

    /**
     * Gets to_name
     *
     * @return string
     */
    public function getToName()
    {
        return $this->container['to_name'];
    }

    /**
     * Sets to_name
     *
     * @param string $to_name Optional: Name of the recipient
     *
     * @return $this
     */
    public function setToName($to_name)
    {
        $this->container['to_name'] = $to_name;

        return $this;
    }

    /**
     * Gets from_phone_number
     *
     * @return string
     */
    public function getFromPhoneNumber()
    {
        return $this->container['from_phone_number'];
    }

    /**
     * Sets from_phone_number
     *
     * @param string $from_phone_number Optional: Phone number of the sender
     *
     * @return $this
     */
    public function setFromPhoneNumber($from_phone_number)
    {
        $this->container['from_phone_number'] = $from_phone_number;

        return $this;
    }

    /**
     * Gets to_phone_number
     *
     * @return string
     */
    public function getToPhoneNumber()
    {
        return $this->container['to_phone_number'];
    }

    /**
     * Sets to_phone_number
     *
     * @param string $to_phone_number Optional: Phone number of the recipient
     *
     * @return $this
     */
    public function setToPhoneNumber($to_phone_number)
    {
        $this->container['to_phone_number'] = $to_phone_number;

        return $this;
    }

    /**
     * Gets from_email_address
     *
     * @return string
     */
    public function getFromEmailAddress()
    {
        return $this->container['from_email_address'];
    }

    /**
     * Sets from_email_address
     *
     * @param string $from_email_address Optional: Email address of the sender
     *
     * @return $this
     */
    public function setFromEmailAddress($from_email_address)
    {
        $this->container['from_email_address'] = $from_email_address;

        return $this;
    }

    /**
     * Gets to_email_address
     *
     * @return string
     */
    public function getToEmailAddress()
    {
        return $this->container['to_email_address'];
    }

    /**
     * Sets to_email_address
     *
     * @param string $to_email_address Optional: Email address of the recipient
     *
     * @return $this
     */
    public function setToEmailAddress($to_email_address)
    {
        $this->container['to_email_address'] = $to_email_address;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


