<?php
/**
 * PriorHistoryItem
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * PriorHistoryItem Class Doc Comment
 *
 * @category Class
 * @description A single message in the prior conversation history
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PriorHistoryItem implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PriorHistoryItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'input_string' => 'string',
        'from_name' => 'string',
        'to_name' => 'string',
        'from_phone_number' => 'string',
        'to_phone_number' => 'string',
        'from_email_address' => 'string',
        'to_email_address' => 'string',
        'trusted_party' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'input_string' => null,
        'from_name' => null,
        'to_name' => null,
        'from_phone_number' => null,
        'to_phone_number' => null,
        'from_email_address' => null,
        'to_email_address' => null,
        'trusted_party' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'input_string' => 'InputString',
        'from_name' => 'FromName',
        'to_name' => 'ToName',
        'from_phone_number' => 'FromPhoneNumber',
        'to_phone_number' => 'ToPhoneNumber',
        'from_email_address' => 'FromEmailAddress',
        'to_email_address' => 'ToEmailAddress',
        'trusted_party' => 'TrustedParty'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'input_string' => 'setInputString',
        'from_name' => 'setFromName',
        'to_name' => 'setToName',
        'from_phone_number' => 'setFromPhoneNumber',
        'to_phone_number' => 'setToPhoneNumber',
        'from_email_address' => 'setFromEmailAddress',
        'to_email_address' => 'setToEmailAddress',
        'trusted_party' => 'setTrustedParty'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'input_string' => 'getInputString',
        'from_name' => 'getFromName',
        'to_name' => 'getToName',
        'from_phone_number' => 'getFromPhoneNumber',
        'to_phone_number' => 'getToPhoneNumber',
        'from_email_address' => 'getFromEmailAddress',
        'to_email_address' => 'getToEmailAddress',
        'trusted_party' => 'getTrustedParty'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['input_string'] = isset($data['input_string']) ? $data['input_string'] : null;
        $this->container['from_name'] = isset($data['from_name']) ? $data['from_name'] : null;
        $this->container['to_name'] = isset($data['to_name']) ? $data['to_name'] : null;
        $this->container['from_phone_number'] = isset($data['from_phone_number']) ? $data['from_phone_number'] : null;
        $this->container['to_phone_number'] = isset($data['to_phone_number']) ? $data['to_phone_number'] : null;
        $this->container['from_email_address'] = isset($data['from_email_address']) ? $data['from_email_address'] : null;
        $this->container['to_email_address'] = isset($data['to_email_address']) ? $data['to_email_address'] : null;
        $this->container['trusted_party'] = isset($data['trusted_party']) ? $data['trusted_party'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets input_string
     *
     * @return string
     */
    public function getInputString()
    {
        return $this->container['input_string'];
    }

    /**
     * Sets input_string
     *
     * @param string $input_string The text content of this historical message
     *
     * @return $this
     */
    public function setInputString($input_string)
    {
        $this->container['input_string'] = $input_string;

        return $this;
    }

    /**
     * Gets from_name
     *
     * @return string
     */
    public function getFromName()
    {
        return $this->container['from_name'];
    }

    /**
     * Sets from_name
     *
     * @param string $from_name Optional: Name of the sender
     *
     * @return $this
     */
    public function setFromName($from_name)
    {
        $this->container['from_name'] = $from_name;

        return $this;
    }

    /**
     * Gets to_name
     *
     * @return string
     */
    public function getToName()
    {
        return $this->container['to_name'];
    }

    /**
     * Sets to_name
     *
     * @param string $to_name Optional: Name of the recipient
     *
     * @return $this
     */
    public function setToName($to_name)
    {
        $this->container['to_name'] = $to_name;

        return $this;
    }

    /**
     * Gets from_phone_number
     *
     * @return string
     */
    public function getFromPhoneNumber()
    {
        return $this->container['from_phone_number'];
    }

    /**
     * Sets from_phone_number
     *
     * @param string $from_phone_number Optional: Phone number of the sender
     *
     * @return $this
     */
    public function setFromPhoneNumber($from_phone_number)
    {
        $this->container['from_phone_number'] = $from_phone_number;

        return $this;
    }

    /**
     * Gets to_phone_number
     *
     * @return string
     */
    public function getToPhoneNumber()
    {
        return $this->container['to_phone_number'];
    }

    /**
     * Sets to_phone_number
     *
     * @param string $to_phone_number Optional: Phone number of the recipient
     *
     * @return $this
     */
    public function setToPhoneNumber($to_phone_number)
    {
        $this->container['to_phone_number'] = $to_phone_number;

        return $this;
    }

    /**
     * Gets from_email_address
     *
     * @return string
     */
    public function getFromEmailAddress()
    {
        return $this->container['from_email_address'];
    }

    /**
     * Sets from_email_address
     *
     * @param string $from_email_address Optional: Email address of the sender
     *
     * @return $this
     */
    public function setFromEmailAddress($from_email_address)
    {
        $this->container['from_email_address'] = $from_email_address;

        return $this;
    }

    /**
     * Gets to_email_address
     *
     * @return string
     */
    public function getToEmailAddress()
    {
        return $this->container['to_email_address'];
    }

    /**
     * Sets to_email_address
     *
     * @param string $to_email_address Optional: Email address of the recipient
     *
     * @return $this
     */
    public function setToEmailAddress($to_email_address)
    {
        $this->container['to_email_address'] = $to_email_address;

        return $this;
    }

    /**
     * Gets trusted_party
     *
     * @return bool
     */
    public function getTrustedParty()
    {
        return $this->container['trusted_party'];
    }

    /**
     * Sets trusted_party
     *
     * @param bool $trusted_party Optional: True if this message is from a trusted party (such as our own company), false otherwise
     *
     * @return $this
     */
    public function setTrustedParty($trusted_party)
    {
        $this->container['trusted_party'] = $trusted_party;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


