<?php
/**
 * AdvancedEmailDetectionRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AdvancedEmailDetectionRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Request to detect phishing from an email
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AdvancedEmailDetectionRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AdvancedEmailDetectionRequest"
     */
    public function testAdvancedEmailDetectionRequest()
    {
    }

    /**
     * Test attribute "from_email_address"
     */
    public function testPropertyFromEmailAddress()
    {
    }

    /**
     * Test attribute "to_email_address"
     */
    public function testPropertyToEmailAddress()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }

    /**
     * Test attribute "html_body"
     */
    public function testPropertyHtmlBody()
    {
    }

    /**
     * Test attribute "allow_low_reputation_senders"
     */
    public function testPropertyAllowLowReputationSenders()
    {
    }

    /**
     * Test attribute "allow_sanctioned"
     */
    public function testPropertyAllowSanctioned()
    {
    }

    /**
     * Test attribute "input_email_file"
     */
    public function testPropertyInputEmailFile()
    {
    }
}
