<?php
/**
 * PhishingDetectionAdvancedRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PhishingDetectionAdvancedRequestTest Class Doc Comment
 *
 * @category    Class
 * @description AI advanced phishing detection request
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PhishingDetectionAdvancedRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PhishingDetectionAdvancedRequest"
     */
    public function testPhishingDetectionAdvancedRequest()
    {
    }

    /**
     * Test attribute "input_string"
     */
    public function testPropertyInputString()
    {
    }

    /**
     * Test attribute "text_type"
     */
    public function testPropertyTextType()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }

    /**
     * Test attribute "allow_unsolicited_sales"
     */
    public function testPropertyAllowUnsolicitedSales()
    {
    }

    /**
     * Test attribute "allow_promotional_content"
     */
    public function testPropertyAllowPromotionalContent()
    {
    }

    /**
     * Test attribute "allow_web_urls"
     */
    public function testPropertyAllowWebUrls()
    {
    }

    /**
     * Test attribute "allow_phone_numbers"
     */
    public function testPropertyAllowPhoneNumbers()
    {
    }

    /**
     * Test attribute "allow_email_addresses"
     */
    public function testPropertyAllowEmailAddresses()
    {
    }

    /**
     * Test attribute "provide_url_analysis"
     */
    public function testPropertyProvideUrlAnalysis()
    {
    }

    /**
     * Test attribute "custom_policy_id"
     */
    public function testPropertyCustomPolicyId()
    {
    }

    /**
     * Test attribute "provide_analysis_rationale"
     */
    public function testPropertyProvideAnalysisRationale()
    {
    }

    /**
     * Test attribute "from_name"
     */
    public function testPropertyFromName()
    {
    }

    /**
     * Test attribute "to_name"
     */
    public function testPropertyToName()
    {
    }

    /**
     * Test attribute "from_phone_number"
     */
    public function testPropertyFromPhoneNumber()
    {
    }

    /**
     * Test attribute "to_phone_number"
     */
    public function testPropertyToPhoneNumber()
    {
    }

    /**
     * Test attribute "from_email_address"
     */
    public function testPropertyFromEmailAddress()
    {
    }

    /**
     * Test attribute "to_email_address"
     */
    public function testPropertyToEmailAddress()
    {
    }
}
