<?php
/**
 * PriorHistoryItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PriorHistoryItemTest Class Doc Comment
 *
 * @category    Class
 * @description A single message in the prior conversation history
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PriorHistoryItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PriorHistoryItem"
     */
    public function testPriorHistoryItem()
    {
    }

    /**
     * Test attribute "input_string"
     */
    public function testPropertyInputString()
    {
    }

    /**
     * Test attribute "from_name"
     */
    public function testPropertyFromName()
    {
    }

    /**
     * Test attribute "to_name"
     */
    public function testPropertyToName()
    {
    }

    /**
     * Test attribute "from_phone_number"
     */
    public function testPropertyFromPhoneNumber()
    {
    }

    /**
     * Test attribute "to_phone_number"
     */
    public function testPropertyToPhoneNumber()
    {
    }

    /**
     * Test attribute "from_email_address"
     */
    public function testPropertyFromEmailAddress()
    {
    }

    /**
     * Test attribute "to_email_address"
     */
    public function testPropertyToEmailAddress()
    {
    }

    /**
     * Test attribute "trusted_party"
     */
    public function testPropertyTrustedParty()
    {
    }
}
